### ISSUE TITLE
v3.2.0: RadarrModal, SonarrModal, and Request modal crash on older Chromium (webOS Smart TV) due to Array.prototype.toSorted() — regression from #1805

### ISSUE THREAD

**Issue by mooock** [Fallenbagel/jellyseerr#2936]
### Description

In v3.2.0, three modals crash with a blank error state ("Ops") on older browsers:

Radarr service settings (Settings → Services → Edit Radarr)
Sonarr service settings (Settings → Services → Edit Sonarr)
Request modal (clicking Request on any movie or TV show)

The pages load normally, but opening these three modals fails. The rest of the UI works fine.
Other browsers on the same Seerr instance (Edge 147 on desktop, Chrome on Android) work without issue. Confirmed by rolling back to v3.1.0 on the same instance — all three modals work again.

### Version

Docker image ghcr.io/seerr-team/seerr:v3.2.0

### Steps to Reproduce

Deploy Seerr v3.2.0 via Docker.
Open the Seerr web UI in a browser with Chromium < 110 (e.g., the built-in browser on an LG webOS Smart TV — User-Agent: Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.128 Safari/537.36 SmartTV/10.0 Colt/2.0).
Log in as an admin.
Navigate to Settings → Services → click Edit on the configured Radarr server.
→ Modal fails to render, shows generic error state.
Repeat for Sonarr — same result.
Go back to the main view, open any movie or TV show, and click the Request button.
→ Request modal fails to render, same error state.

### Logs

```shell
Server logs show no errors — all API calls return 200. The crash is client-side in the browser's JS runtime.

Expected browser console error when the affected modals attempt to render:

TypeError: testResponse.profiles.toSorted is not a function

This originates from the `.toSorted(...)` calls introduced in PR #1805 in these files:
- src/components/Settings/RadarrModal/index.tsx (quality profiles dropdown)
- src/components/Settings/SonarrModal/index.tsx (quality profiles dropdown, including anime)
- src/components/RequestModal/AdvancedRequester/index.tsx (quality profile dropdown in request modal)

`Array.prototype.toSorted()` is ES2023 and requires Chrome 110+ / Firefox 115+ / Safari 16+. On older embedded Chromium (webOS TV browser reports as Chromium 94), the method doesn't exist and the modal component throws on render.

Could not capture the console output directly — remote DevTools on this TV model requires LG Developer Mode, which wasn't worth setting up given the root cause was already identifiable from the code.
```

### Platform

desktop

### Database

SQLite (default)

### Device

LG OLED77C34LA

### Operating System

SmartTV/10.0

### Browser

TV Browser

### Additional Context

PR #1805 introduced Array.prototype.toSorted() (ES2023) in three frontend components. TypeScript does not transpile runtime methods, so the calls ship as-is to the browser. Compatibility was flagged during PR review (CodeRabbit comment) but not addressed before merge. tsconfig.json still targets ES2021.
The one-line fix is to swap .toSorted((a,b) => ...) for [...arr].sort((a,b) => ...) in the three files — identical behavior, ES2015-compatible, no other changes needed.
Precedent in the Seerr project
The seerr-team/mobile-app repo already ships a toSorted polyfill (v0.10.4 release notes: "Add polyfill for toSorted method"), presumably for the same class of older embedded browsers on TV devices. The same consideration applies to the web app rendered in TV browsers.
Bisect

v3.0.0 → works
v3.1.0 → works
v3.2.0 → broken

PR #1805 merged between v3.1.0 and v3.2.0.
Environment

Docker: ghcr.io/seerr-team/seerr:v3.2.0
Database: SQLite (default)
Reverse proxy: Nginx Proxy Manager
Client: LG webOS Smart TV, built-in browser (UA: Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.128 Safari/537.36 SmartTV/10.0 Colt/2.0)
Currently pinned to v3.1.0 as a workaround

### Search Existing Issues

- [x] Yes, I have searched existing issues.

### Code of Conduct

- [x] I agree to follow Seerr's Code of Conduct

**Comment by gauthier-th** [comment]
Thanks for the report. We are closing this issue as Chrome 94 is 5 years old and no longer supported. Dropping support for older browsers allows us to adopt the latest web standards and focus on delivering new features. For your own security and to use our app properly, we strongly encourage updating your browser to a modern version

**Comment by mooock** [comment]
To confirm. newest LG webos works. with 3.2.0. so maybe it could be added to the requirements which browser version is required.

**Comment by fallenbagel** [comment]
> To confirm. newest LG webos works. with 3.2.0. so maybe it could be added to the requirements which browser version is required.

Seerr was never designed for TVs. It never officially supported TV oses and could not support them either with how old the browsers are. We can't possibly downgrade dependencies and code to support old unsupported, unmaintained browsers. https://endoflife.date/chrome

The only one with tv support is: https://github.com/seerr-team/mobile-app but that too android TV. Seerr was first and foremost designed to be used on desktop/mobile.

**Comment by gauthier-th** [comment]
> To confirm. newest LG webos works. with 3.2.0. so maybe it could be added to the requirements which browser version is required.

Browser versions change really fast. It is not practical for us to maintain a list of compatible browsers.
For security reasons, the standard practice is to keep browsers continuously updated, which is why browser providers themselves offer very short support windows for older versions.
