### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by nerethos** [fallenbagel/jellyseerr#1441]
### Description

I run jellyseerr as a docker container behind traefik reverse proxy with SSL. Since updating to 2.4.0, the app is inaccessible with the error `{ "message": "invalid csrf token" }`.

Rolling back to 2.3.0, or disabling CSRF protection, resolves the issue.

### Version

2.4.0

### Steps to Reproduce

See above

### Logs

```shell

```

### Platform

desktop

### Database

SQLite (default)

### Device

Any

### Operating System

Any

### Browser

Any

### Code of Conduct

- [x] I agree to follow Jellyseerr's Code of Conduct

**Comment by fallenbagel** [comment]
https://github.com/fallenbagel/jellyseerr/pull/1393

It's probably this. I'll make a preview with a fix can you test when I deploy?

**Comment by fallenbagel** [comment]
The fix for this should be available as a test in `preview-csrf-protection-fix` tag (in about 5 minutes)

**Comment by mrplow** [comment]
Darn, I had the same issue and preview-csrf-protection-fix didn't work for me.
Back to 2.3.0 for now.

```
jellyseerr  | > jellyseerr@0.1.0 start /app
jellyseerr  | > NODE_ENV=production node dist/index.js
jellyseerr  | 
jellyseerr  | 2025-03-10T23:07:39.330Z [info]: Commit Tag: 71db5842732253b5fb13adda13e578044736806c 
jellyseerr  | node:internal/modules/cjs/loader:1228
jellyseerr  |   throw err;
jellyseerr  |   ^
jellyseerr  | 
jellyseerr  | Error: Cannot find module 'csurf'
jellyseerr  | Require stack:
jellyseerr  | - /app/dist/index.js
jellyseerr  |     at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
jellyseerr  |     at Function._load (node:internal/modules/cjs/loader:1055:27)
jellyseerr  |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
jellyseerr  |     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
jellyseerr  |     at Module.require (node:internal/modules/cjs/loader:1311:12)
jellyseerr  |     at require (node:internal/modules/helpers:136:16)
jellyseerr  |     at Object.<anonymous> (/app/dist/index.js:59:33)
jellyseerr  |     at Module._compile (node:internal/modules/cjs/loader:1554:14)
jellyseerr  |     at Object..js (node:internal/modules/cjs/loader:1706:10)
jellyseerr  |     at Module.load (node:internal/modules/cjs/loader:1289:32) {
jellyseerr  |   code: 'MODULE_NOT_FOUND',
jellyseerr  |   requireStack: [ '/app/dist/index.js' ]
jellyseerr  | }
jellyseerr  | 
jellyseerr  | Node.js v22.14.0
jellyseerr  |  ELIFECYCLE  Command failed with exit code 1.
jellyseerr exited with code 1
```

**Comment by fallenbagel** [comment]
> Darn, I had the same issue and preview-csrf-protection-fix didn't work for me. Back to 2.3.0 for now.
> 
> ```
> jellyseerr  | > jellyseerr@0.1.0 start /app
> jellyseerr  | > NODE_ENV=production node dist/index.js
> jellyseerr  | 
> jellyseerr  | 2025-03-10T23:07:39.330Z [info]: Commit Tag: 71db5842732253b5fb13adda13e578044736806c 
> jellyseerr  | node:internal/modules/cjs/loader:1228
> jellyseerr  |   throw err;
> jellyseerr  |   ^
> jellyseerr  | 
> jellyseerr  | Error: Cannot find module 'csurf'
> jellyseerr  | Require stack:
> jellyseerr  | - /app/dist/index.js
> jellyseerr  |     at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
> jellyseerr  |     at Function._load (node:internal/modules/cjs/loader:1055:27)
> jellyseerr  |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
> jellyseerr  |     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
> jellyseerr  |     at Module.require (node:internal/modules/cjs/loader:1311:12)
> jellyseerr  |     at require (node:internal/modules/helpers:136:16)
> jellyseerr  |     at Object.<anonymous> (/app/dist/index.js:59:33)
> jellyseerr  |     at Module._compile (node:internal/modules/cjs/loader:1554:14)
> jellyseerr  |     at Object..js (node:internal/modules/cjs/loader:1706:10)
> jellyseerr  |     at Module.load (node:internal/modules/cjs/loader:1289:32) {
> jellyseerr  |   code: 'MODULE_NOT_FOUND',
> jellyseerr  |   requireStack: [ '/app/dist/index.js' ]
> jellyseerr  | }
> jellyseerr  | 
> jellyseerr  | Node.js v22.14.0
> jellyseerr  |  ELIFECYCLE  Command failed with exit code 1.
> jellyseerr exited with code 1
> ```

Because you'll need to repull the image. This was fixed just now

**Comment by mrplow** [comment]
Perfect, works now. 
Thanks
